---
title: "Italian COVID19 Monitor"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
require(covid19)
require(dplyr)
require(flexdashboard)
require(highcharter)
require(magrittr)

# Building of the COVID19 object
covid <- Covid$new()$update()
```

Sidebar {.sidebar}
=======================================================================

This is a dashboard representing the outbreak and spread of COVID-19 in
Italy.

Forecasts are computed for **deaths** and **total cases** only, based on
exponential models.

```{r}
selectInput(
  inputId = 'log-scale',
  label = 'Please select a scale:',
  choices = list('Linear' = FALSE, 'Logarithmic' = TRUE),
  multiple = FALSE,
  selectize = FALSE
)
```

Prepared with &hearts; by [Hypermynds](www.hypermynds.com).

Dashboard
=======================================================================

Row
-----------------------------------------------------------------------

### Total Cases {.value-box}

```{r}
renderValueBox({
  total_cases <- covid$get() %>%
      tail(1) %>% 
      pull(totale_casi) %>%
      format(big.mark = '.', decimal.mark = ',')
  valueBox(
    value = total_cases,
    icon = "fa-users"
  )
})
```

### Recovered {.value-box}

```{r}
renderValueBox({
  recovered <- covid$get() %>%
      tail(1) %>% 
      pull(dimessi_guariti) %>%
      format(big.mark = '.', decimal.mark = ',')
  valueBox(
    value = recovered,
    icon = "fa-thumbs-up"
  )
})
```

### Deaths {.value-box}

```{r}
renderValueBox({
  deaths <- covid$get() %>%
      tail(1) %>% 
      pull(deceduti) %>%
      format(big.mark = '.', decimal.mark = ',')
  valueBox(
    value = deaths,
    icon = "fa-times",
    color = 'warning'
  )
})
```

Row
-----------------------------------------------------------------------

### Historical Analysis

```{r}
renderHighchart({
  covid$plot_hist(input[['log-scale']])
})
```

### Forecast Analysis

```{r}
renderHighchart({
  covid$plot_fore(input[['log-scale']])
})
```

Raw Data
=======================================================================

```{r}
renderTable({
  covid$table()
})
```
